In [1]:
a=5
isinstance(a, int)

True

In [8]:
a=[1,2,3]
iter(a)


In [16]:
from datetime import datetime, date, time

dt=datetime(2022, 3, 16, 20, 30, 41)
dt.weekday()

2

In [17]:
dt.time()

datetime.time(20, 30, 41)

In [20]:
# convert datetime to string:
dt.strftime('%m/%d/%Y %H:%M')

'03/16/2022 20:30'

In [24]:
# convert string to datetime:
datetime.strptime('2020/03/15', '%Y/%m/%d')

datetime.datetime(2020, 3, 15, 0, 0)

In [26]:
# delta = the difference between two periods:
dt2=datetime(2022, 3, 18, 22, 20, 0)
delta=dt2-dt
delta

datetime.timedelta(days=2, seconds=6559)

In [34]:
# unpacking tuple:
a=['a', 'b', 'c', 'd']
b=[0,1,2,3]
tupl=zip(a,b)
list(tupl)

[('a', 0), ('b', 1), ('c', 2), ('d', 3)]

In [46]:
j=[]
i=[]
for x, y in zip(a,b):
#     print(x)
    j.append(x)
    i.append(y)
    
i
j

['a', 'b', 'c', 'd']

In [47]:
x='string'
tuple(x)

('s', 't', 'r', 'i', 'n', 'g')

In [49]:
# tuple is inmutable, but If an object inside a tuple is mutable, such as a list, you can modify it in-place:
y=tuple(('xxx', [1,2,3], True))
y[1].append(4)
y

('xxx', [1, 2, 3, 4], True)

Checking whether a list contains a value is a lot slower than doing so with dicts and sets, as Python makes a linear scan across the values of the list, whereas it can check the others (based on hash tables) in constant time.

extend vs concatenate:
concatenation - is more expensive, 

In [51]:
# zip can take an arbitrary number of sequences, and the number of elements it produces is determined by the shortest sequence:
a=(1,2,3,4,5)
b=("a", "b", "c", "d")
zipped_a_b=zip(a,b)
list(zipped_a_b)

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [64]:
# creating dictionary depending on the first letter - 3 ways:
words = ['apple', 'bat', 'bar', 'atom', 'book', 'dog']
letters1={}
letters2={}

for word in words:
    letter=word[0]
    if letter not in letters1:
        letters1[letter]=[word]
    else:
        letters1[letter].append(word)       

# or using setdefault method:
for word in words:
    letter=word[0]
    letters2.setdefault(letter, []).append(word)

# or using defaultdict method - as an argument is passed type or function for generating the default value for each slot 
# in the dict:
from collections import defaultdict

letters3=defaultdict(list)
for word in words:
    letters3[word[0]].append(word)
    
print(letters1==letters2==letters3)
letters1

True


{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book'], 'd': ['dog']}

In [65]:
# in a dictionary keys must be hashable = immutable object - using hash function:
hash((1,2,(3,4)))

3794340727080330424

In [67]:
try:
    hash((1,2,[3,4]))
except (TypeError):
    print('Type is mutable hence hash function does not work')
    
# to use list as a key - first must be converted into tuple

Type is mutable hence hash function does not work


In [70]:
#set - is an unordered collection of unique elements, created by using set function or curly braces:
a=set([1,2,2,4,5,5,1,1,6])
b={1,2,2,4,5,5,1,1,6}
print(f'a={a}\nb={b}\n"a" is equal "b" - {a==b}')

a={1, 2, 4, 5, 6}
b={1, 2, 4, 5, 6}
"a" is equal "b" - True


In [74]:
# set supports operations like e.g. union, intersection, difference:
x=set([5,5,4,7,7,7,3])
y=set([10,1,1,4,4,4,8,5])
x.union(y) # combines unique elements from each set

{1, 3, 4, 5, 7, 8, 10}

In [76]:
# elements occuring in both sets:
x.intersection(y) #or:
x & y

{4, 5}

In [77]:
# set -> issubset = is contained in another set or issuperset = contains all elements of another set
a= set([1, 2, 3, 4, 5])
a.issubset({1,2,3})

False

In [78]:
({1,2,3}).issubset(a)

True

In [79]:
a.issuperset({1,2,3}) # a contains all: 1,2 and 3

True

In [85]:
# list of lists , 2 for loops:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
            ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

desired_list=[]
for names in all_data:
    [desired_list.append(name) for name in names if name.count('a')>=2] 

desired_list

['Maria', 'Natalia']

In [87]:
# shorter form:
result=[name for names in all_data for name in names if name.count('a')>=2]
result

['Maria', 'Natalia']

In [88]:
# flatten tuples:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flatten=[x for tup in some_tuples for x in tup]
flatten

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
# nested list:
nested=[[x for x in tup] for tup in some_tuples]
nested

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [100]:
# function to clean list of strings:
import re # module ReGex 

states = [' Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda', 'south carolina##', 'West virginia?']

def clear_list(lista):
    result=[]
    for string in lista:
        string=string.strip() # removing both the leading and the trailing characters (based on the string argument passed)
        string=re.sub('[#?!]', '', string) # substitutes special characters
        string=string.title() #uppercase first letter
        result.append(string)
    return result

clear_list(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [105]:
# ANONYMOUS = LAMBDA FUNCTIONS - writing functions consisting of a single statement, lambda keyword = function declaration

def multipl(x):
    return x*2

# or with lambda:
result=lambda x: x*2
print(f'multipl function: {multipl(4)}\nlambda: {result(4)}')

multipl function: 8
lambda: 8


In [113]:
# sort a collection of strings by the number of distinct letters in each string:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']
strings.sort(key= lambda x: len(set(list(x))))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

In [ ]:
# opening file - When you use open to create file objects, it is important to explicitly close the file when you are finished
# with it. Closing the file releases its resources back to the operating system:

f=open(path)
for line in f:
    ...

f.close()

# writing 'with' - will automatically close opened file when exiting the with block
with open(path) as f:
    line=[x.rstrip() for x in f]

In [116]:
# ***********************************************NUMPY:
import numpy as np

arr=np.arange(10)
arr.astype('float') # creates new array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [117]:
# any modification to the array slices are performed on the original array; if should be made on its copy - the copy() method
# must be explicitly used:
arr=np.arange(10)
arr[5:8]=100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [129]:
arr=np.arange(12).reshape(3,4)

In [134]:
arr=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # size important!
mask=arr=='Bob'
mask

arr2=np.random.randn(7,4)
arr2[mask] # returned first and fourth row, where name ='Bob' so was True

array([[-0.34971444, -0.51202619, -0.62722379, -0.53842864],
       [ 0.06941134,  0.14198311, -1.39175588,  0.48052904]])

In [139]:
x= np.empty((8,4))
for i in range(8):
    x[i]=i
x

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [140]:
# fancy indexing - indexing by numpy array
x[[3,2,1,4]]



array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [4., 4., 4., 4.]])

In [147]:
# transposition:
x=np.random.randn(3,4)
x.T

array([[-1.07463763,  0.57837833, -0.59195422],
       [ 0.81506038,  2.22786094,  1.02957917],
       [-0.08427387, -0.16771877,  2.0505956 ],
       [-1.98426804,  1.20041315,  0.70435987]])

In [156]:
# UNIVERSAL FUNCTIONS = UFUNC -> function that performs element wise operations on data in ndarrays:
rng=np.random.RandomState(0)
x=rng.rand(7)*8
reminder, whole_part=np.modf(x) # splits array on two separate arrays with reminder and whole number)
print(x)
print(reminder)

[4.39050803 5.72151493 4.82210701 4.35906546 3.38923839 5.1671529
 3.50069769]
[0.39050803 0.72151493 0.82210701 0.35906546 0.38923839 0.1671529
 0.50069769]
